# Generated by Django 5.1.6 on 2025-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('order_gas', 'Order Gas'), ('buy_non_domestic_gas', 'Buy Non-Domestic Gas'), ('subsidy_voluntarily', 'Subsidy Voluntarily'), ('locate_distributor', 'Locate Distributor')], max_length=50),
        ),
    ]
