# Generated by Django 5.1.6 on 2025-02-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_name_customer_full_name_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
